dasMVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dasMVC.Controllers
{
	[Authorize(Roles = "admin")]
	public class AdminController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

dasMVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dasMVC.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

dasMVC/Controllers/DoctorController.cs
using dasMVC.Entities;
using dasMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace dasMVC.Controllers
{
	[Authorize(Roles = "admin")]
	public class DoctorController : Controller
	{
		private readonly DatabaseContext _databaseContext;

		public DoctorController(DatabaseContext databaseContext)
		{
			_databaseContext = databaseContext;
		}

		public IActionResult Index()
		{
			List<DoctorViewModel> doctors = _databaseContext.Doctors
				.Include(d => d.Department)
				.Select(d => new DoctorViewModel
				{
					DoctorId = d.DoctorId,
					DoctorName = d.DoctorName,
					DoctorImage = d.DoctorImage,
					DepartmentId = d.DepartmentId,
					Department = new DepartmentModel
					{
						DepartmentId = d.Department.DepartmentId,
						DepartmentName = d.Department.DepartmentName
					}
				})
				.ToList();

			return View(doctors);
		}


        public IActionResult Create()
        {
            List<Department> departments = _databaseContext.Departments.ToList();

			ViewBag.Departments = new SelectList(departments, "DepartmentId", "DepartmentName");

            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateDoctorModel doctorModel)
        {
            if (ModelState.IsValid)
            {
                if (_databaseContext.Doctors.Any(x => x.DoctorName.ToLower() == doctorModel.DoctorName.ToLower()
                && x.DepartmentId == doctorModel.DepartmentId))
                {
                    ModelState.AddModelError(nameof(doctorModel.DepartmentId), "This name corresponds to a doctor in this polyclinic.");
                    return View(doctorModel);
                }

                Doctor doctor = new Doctor
                {
                    DoctorName = doctorModel.DoctorName,
                    DepartmentId = doctorModel.DepartmentId
                };

                _databaseContext.Doctors.Add(doctor);
                _databaseContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Departments = new SelectList(_databaseContext.Departments.ToList(), "DepartmentId", "DepartmentName");

            return View(doctorModel);
        }

		public IActionResult Delete(int id)
		{
			Doctor doctor = _databaseContext.Doctors.Find(id);

			if (doctor != null)
			{
				_databaseContext.Doctors.Remove(doctor);
				_databaseContext.SaveChanges();
			}
			return RedirectToAction(nameof(Index));
		}

	}
}

dasMVC/Controllers/UserController.cs
using AutoMapper;
using dasMVC.Entities;
using dasMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dasMVC.Controllers
{
	[Authorize(Roles = "admin")]
	public class UserController : Controller
    {
		private readonly DatabaseContext _databaseContext;
		private readonly IMapper _mapper;

		public UserController(DatabaseContext databaseContext, IMapper mapper)
		{
			_databaseContext = databaseContext;
			_mapper = mapper;
		}

		public IActionResult Index()
        {
			List<UserModel> users = _databaseContext.Users.ToList().Select(x => _mapper.Map<UserModel>(x)).ToList();

			//_databaseContext.Users.Select(x => new UserModel {Id = x.Id, FullName = x.FullName}).ToList();

            return View(users);
        }

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(CreateUserModel model)
		{
			if(ModelState.IsValid)
			{
				if (_databaseContext.Users.Any(x => x.Username.ToLower() == model.Username.ToLower()))
				{
					ModelState.AddModelError(nameof(model.Username), "Username is already exists.");
					return View(model);
				}

				User user = _mapper.Map<User>(model);
				_databaseContext.Users.Add(user);
				_databaseContext.SaveChanges();

				return RedirectToAction("Appointments", "Appointment");
			}

			return View(model);
		}

		public IActionResult Edit(Guid id)
		{
			User user = _databaseContext.Users.Find(id);
			EditUserModel model = _mapper.Map<EditUserModel>(user);

			return View(model);
		}

		[HttpPost]
		public IActionResult Edit(Guid id, EditUserModel model)
		{
			if (ModelState.IsValid)
			{
				if (_databaseContext.Users.Any(x => x.Username.ToLower() == model.Username.ToLower() && x.Id != id))
				{
					ModelState.AddModelError(nameof(model.Username), "Username is already exists.");
					return View(model);
				}

				User user = _databaseContext.Users.Find(id);

				_mapper.Map(model, user);
				_databaseContext.SaveChanges();

				return RedirectToAction(nameof(Index));
			}

			return View(model);
		}

		public IActionResult Delete(Guid id)
		{
			User user = _databaseContext.Users.Find(id);

			if (user != null)
			{
				_databaseContext.Users.Remove(user);
				_databaseContext.SaveChanges();
			}
			return RedirectToAction(nameof(Index));
		}
	}
}

dasMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Doctor Appointment System</title>
    <link rel="icon" href="/images/dasfav.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
	<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.3.1/css/flag-icon.min.css" rel="stylesheet" />

	<link href="~/css/slider.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border" role="status" style="color: lightseagreen;">
            <span class="sr-only">Yükleniyor...</span>
        </div>
    </div>


    @{
        bool hideHeader = ViewData["HideHeader"] as bool? ?? false;
    }

    @if (!hideHeader)
    {

        <header>
            <nav class="navbar navbar-expand-sm navbar-expand-lg navbar-toggleable-sm navbar-light box-shadow fixed-top">
                <div class="container">
                    <a class="navbar-brand" style="color:lightseagreen; font-weight: bolder; font-size: 25px;" asp-area="" asp-controller="Home" asp-action="Index">
						<img class="img-fluid" width="100px;" src="~/images/das.png" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 align-items-center">
                            <li class="nav-item">
                                <a class="nav-link text-light" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("Home")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("About")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("Department")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" style="font-size: 20px;" asp-area="" asp-controller="Contact" asp-action="Index">@_localization.Getkey("Contact")</a>
                            </li>

                            <li class="nav-item">
                                <div class="dropdown">
                                    <button type="button" class="btn dropdown-toggle text-light" data-bs-toggle="dropdown">@_localization.Getkey("Language")</button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US" class="dropdown-item">
                                                <i class="flag-icon flag-icon-gb"></i>
                                            </a>
                                        </li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="tr-TR" class="dropdown-item">
                                                <i class="flag-icon flag-icon-tr"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("admin"))
                                {

                                    <li class="nav-item dropdown">
                                        <a style="font-size: 20px;" class="nav-link dropdown-toggle text-light" asp-controller="Admin" asp-action="Index" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Administrator
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="User" asp-action="Index">@_localization.Getkey("Users")</a></li>
                                            <li><a class="dropdown-item" asp-controller="Doctor" asp-action="Index">@_localization.Getkey("Doctors")</a></li>
                                            <li><a class="dropdown-item" asp-controller="Department" asp-action="Index">@_localization.Getkey("Deparment")</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li>
                                                <a class="dropdown-item" asp-controller="Appointment" asp-action="Index">@_localization.Getkey("Appointments")</a>
                                            </li>
                                        </ul>
                                    </li>

                                }
                                else
                                {
                                    <li class="nav-item ms-auto btn btn-primary m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Appointment" asp-action="Appointments">
                                            <i class="fa fa-calendar me-2" aria-hidden="true"></i>

                                            @_localization.Getkey("Appointments")
                                        </a>
                                    </li>
                                    <li class="nav-item btn btn-success m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Appointment" asp-action="MyAppointments">
                                            <i class="fa fa-tasks me-2" aria-hidden="true"></i>@_localization.Getkey("MyAppointments")
                                        </a>
                                    </li>
                                }
                                
                                <li class="nav-item ms-auto btn btn-mysuccess m-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Profile"><i class="fa-solid fa-user me-2"></i>@User.FindFirst("Username").Value</a>
                                </li>
                                <li class="nav-item btn btn-danger m-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>@_localization.Getkey("Logout")</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item ms-auto btn btn-mysuccess m-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>@_localization.Getkey("Login")</a>
                                </li>
                                <li class="nav-item btn btn-primary m-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register"><i class="fa-solid fa-user me-2"></i>@_localization.Getkey("Register")</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

    }



            @RenderBody()


    @{
        bool hideFooter = ViewData["HideFooter"] as bool? ?? false;
    }

    @if (!hideFooter)
        {

    <footer>
            <div style="bottom:0; width:100%; background-color: #68c3cf;" class="text-light text-center">

            <div class="row">
                    <div class="col-12">
                        <div class="container text-center p-4">
                            2023 - Doctor Appointment System
                        </div>
                    </div>
            </div>
        </div>
    </footer>
        }

	<script src="~/lib/jquery/dist/jquery-3.6.0.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/toastr.js/toastr.min.js"></script>
	<script src="~/js/slider.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
	
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

dasMVC/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Doctor Appointment System</title>
    <link rel="icon" href="/images/dasfav.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.3.1/css/flag-icon.min.css" rel="stylesheet" />

    <link href="~/css/slider.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border" role="status" style="color: lightseagreen;">
            <span class="sr-only">Yükleniyor...</span>
        </div>
    </div>


    @{
        bool hideHeader = ViewData["HideHeader"] as bool? ?? false;
    }

    @if (!hideHeader)
    {

        <header class="mb-5">
            <nav class="navbar navbar-expand-lg navbar-dark bg-light sticky-top box-shadow">
                <div class="container">
                    <a class="navbar-brand" style="color:lightseagreen; font-weight: bolder; font-size: 25px;" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="img-fluid" width="100px;" src="~/images/das.png" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 align-items-center">
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("Home")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("About")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="Index">@_localization.Getkey("Department")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="font-size: 20px;" asp-area="" asp-controller="Contact" asp-action="Index">@_localization.Getkey("Contact")</a>
                            </li>

                            <li class="nav-item">
                                <div class="dropdown">
                                    <button type="button" class="btn dropdown-toggle text-dark" data-bs-toggle="dropdown">@_localization.Getkey("Language")</button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US" class="dropdown-item">
                                                <i class="flag-icon flag-icon-gb"></i>
                                            </a>
                                        </li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="tr-TR" class="dropdown-item">
                                                <i class="flag-icon flag-icon-tr"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("admin"))
                                {

                                    <li class="nav-item dropdown">
                                        <a style="font-size: 20px;" class="nav-link dropdown-toggle text-dark" asp-controller="Admin" asp-action="Index" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Administrator
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="User" asp-action="Index">@_localization.Getkey("Users")</a></li>
                                            <li><a class="dropdown-item" asp-controller="Doctor" asp-action="Index">@_localization.Getkey("Doctors")</a></li>
                                            <li><a class="dropdown-item" asp-controller="Department" asp-action="Index">@_localization.Getkey("Deparment")</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li>
                                                <a class="dropdown-item" asp-controller="Appointment" asp-action="Index">@_localization.Getkey("Appointment")</a>
                                            </li>
                                        </ul>
                                    </li>

                                    <li class="nav-item btn ms-auto btn-mysuccess m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Profile"><i class="fa-solid fa-user me-2"></i>@User.FindFirst("Username").Value</a>
                                    </li>
                                    <li class="nav-item btn btn-danger m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>@_localization.Getkey("Logout")</a>
                                    </li>

                                }
                                else
                                {
                                    <li class="nav-item ms-auto btn btn-primary m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Appointment" asp-action="Appointments">
                                            <i class="fa fa-calendar me-2" aria-hidden="true"></i>
                                            @_localization.Getkey("Appointments")
                                            </a>
                                    </li>
                                    <li class="nav-item btn btn-success m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Appointment" asp-action="MyAppointments">
                                            <i class="fa fa-tasks me-2" aria-hidden="true"></i>@_localization.Getkey("MyAppointments")
                                        </a>
                                    </li>

                                    <li class="nav-item btn btn-mysuccess m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Profile">
                                            <i class="fa-solid fa-user me-2"></i>@User.FindFirst("Username").Value
                                        </a>
                                    </li>
                                    <li class="nav-item btn btn-danger m-2">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">
                                            <i class="fa-solid fa-right-from-bracket me-2"></i>@_localization.Getkey("Logout")
                                        </a>
                                    </li>
                                }
                                
                            }
                            else
                            {
                                <li class="nav-item ms-auto btn btn-mysuccess m-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>@_localization.Getkey("Login")</a>
                                </li>
                                <li class="nav-item btn btn-primary m-2">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register"><i class="fa-solid fa-user me-2"></i>@_localization.Getkey("Register")</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

    }



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    @{
        bool hideFooter = ViewData["HideFooter"] as bool? ?? false;
    }

    @if (!hideFooter)
    {

        <footer>
            <div style="bottom:0; width:100%;">
                <div class="container text-center">
                    
                </div>
            </div>
        </footer>
    }

    <script src="~/lib/jquery/dist/jquery-3.6.0.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/slider.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

dasMVC/Views/Shared/_SliderPartial.cshtml
<section class="section swiper-container swiper-slider swiper-slider-1 context-dark js-fullheight" data-loop="true" data-autoplay="5000" data-simulate-touch="false">
    <div class="swiper-wrapper">
        <div class="swiper-slide" data-slide-bg="images/slider2.jpg">
            <div class="swiper-slide-caption section-lg">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-7 mx-auto">
                            <h1>
                                <span style="color: lightseagreen;" class="d-block text-center" data-caption-animate="fadeInUp" data-caption-delay="100">
                                    @_localization.Getkey("Slider21")
                                </span>
                                <span style="color: #ffffff;" class="d-block text-center" data-caption-animate="fadeInUp" data-caption-delay="200">
                                    @_localization.Getkey("Slider22")
                                </span>
                            </h1>
                            <p style="color: #ffffff;" class="d-block text-center" data-caption-animate="fadeInUp" data-caption-delay="350">@_localization.Getkey("Slider23")</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-slide" data-slide-bg="images/slider1.jpg">
            <div class="swiper-slide-caption section-lg">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-7 mx-auto">
                            <h1>
                                <span style="color: lightseagreen;" class="d-block text-center" data-caption-animate="fadeInUp" data-caption-delay="100">
                                    @_localization.Getkey("Slider11")
                                </span>
                                <span style="color: #ffffff;" class="d-block text-center" data-caption-animate="fadeInUp" data-caption-delay="200">
                                    @_localization.Getkey("Slider12")
                                </span>
                            </h1>
                            <p style="color: #ffffff" class="d-block text-center" data-caption-animate="fadeInUp " data-caption-delay="350">@_localization.Getkey("Slider13")</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-pagination-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-lg-7 mx-auto">
                    <div class="swiper-pagination"></div>
                </div>
            </div>
        </div>
    </div>
</section>